version: '2'
services:
  product_postgres_db:
    container_name: product_postgres_db
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - product_pgvolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  product_pgvolume:
