spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
  jpa:
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    url: jdbc:postgresql://localhost:5432/product
    user: postgres
    schemas: product
